export const NOVEL_SEARCH = 'NOVEL_SEARCH'
export const NOVEL_SEARCH_SUCCESS = 'NOVEL_SEARCH_SUCCESS'
export const NOVEL_SEARCH_ERROR = 'NOVEL_SEARCH_ERROR'
export const NOVEL_UPDATE_FAV = 'NOVEL_UPDATE_FAVORITE'
